apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-sync
  namespace: digitaltwin
  labels:
    app: cluster-sync
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cluster-sync
  template:
    metadata:
      labels:
        app: cluster-sync
    spec:
      serviceAccountName: cluster-sync-sa
      containers:
        - name: cluster-sync
          image: 790304249797.dkr.ecr.ap-south-1.amazonaws.com/digitaltwin/cluster-sync:latest
          ports:
            - containerPort: 8083
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: mysql-secret
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "300m"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 60
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: cluster-sync
  namespace: digitaltwin
spec:
  selector:
    app: cluster-sync
  ports:
    - port: 8083
      targetPort: 8083
  type: ClusterIP

