apiVersion: apps/v1
kind: Deployment
metadata:
  name: cost-service
  namespace: digitaltwin
  labels:
    app: cost-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cost-service
  template:
    metadata:
      labels:
        app: cost-service
    spec:
      containers:
        - name: cost-service
          image: 790304249797.dkr.ecr.ap-south-1.amazonaws.com/digitaltwin/cost-service:latest
          ports:
            - containerPort: 8086
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: mysql-secret
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "300m"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8086
            initialDelaySeconds: 60
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8086
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: cost-service
  namespace: digitaltwin
spec:
  selector:
    app: cost-service
  ports:
    - port: 8086
      targetPort: 8086
  type: ClusterIP

