server:
  port: 8085

spring:
  application:
    name: simulation-service
  datasource:
    url: jdbc:mysql://localhost:3306/digital_twin_platform?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: Koushik@2004
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  cache:
    type: redis
    redis:
      time-to-live: 600000
      cache-null-values: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    org:
      springframework: INFO
