apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: digitaltwin
type: Opaque
stringData:
  JWT_SECRET_KEY: "DT@JWTSecretKey2024!SuperSecure256BitKey!!"
  JWT_EXPIRATION_MS: "86400000"
