apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: monitoring
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "DT@RootPass2024!"
  MYSQL_PASSWORD: "DT@UserPass2024!"
  MYSQL_USER: "dtadmin"
  MYSQL_DATABASE: "digitaltwin"
