apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: digitaltwin
data:
  SPRING_DATASOURCE_URL: "jdbc:mysql://virtual-infra-db.monitoring.svc.cluster.local:3306/digitaltwin?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
  SPRING_DATASOURCE_USERNAME: "dtadmin"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_JPA_DATABASE_PLATFORM: "org.hibernate.dialect.MySQL8Dialect"
  EUREKA_ENABLED: "false"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,prometheus,metrics"
  MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: "always"
  JAVA_OPTS: "-Xms256m -Xmx512m -XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0"
  API_GATEWAY_URL: "http://api-gateway.digitaltwin.svc.cluster.local:8080"
  AUTH_SERVICE_URL: "http://auth-service.digitaltwin.svc.cluster.local:8081"
  CLUSTER_SYNC_URL: "http://cluster-sync.digitaltwin.svc.cluster.local:8082"
  TOPOLOGY_SERVICE_URL: "http://topology-service.digitaltwin.svc.cluster.local:8083"
  SIMULATION_SERVICE_URL: "http://simulation-service.digitaltwin.svc.cluster.local:8084"
  RISK_SERVICE_URL: "http://risk-service.digitaltwin.svc.cluster.local:8085"
  COST_SERVICE_URL: "http://cost-service.digitaltwin.svc.cluster.local:8086"
  AI_SERVICE_URL: "http://ai-service.digitaltwin.svc.cluster.local:8000"
